name: Añadir nuevo paquete
description: Propón un nuevo script de instalación para el registro.
title: "[Package]: "
body:
  - type: input
    id: package_name
    attributes:
      label: Nombre del paquete
      description: Un nombre corto y único (ej. mi-herramienta).
      placeholder: mi-paquete
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: ¿Qué hace este paquete?
      placeholder: Instala la configuración de desarrollo...
    validations:
      required: true
  - type: input
    id: script_url
    attributes:
      label: URL del script de instalación
      description: Enlace RAW al script ejecutable (ej. enlace de GitHub Raw).
      placeholder: https://raw.githubusercontent.com/.../install.sh
    validations:
      required: true
